name: Bug Report
description: Submit a bug report.
labels: bug
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the bug is, and why you consider it to be a bug.
    validations:
      required: true
  - type: dropdown
    id: flavour
    attributes:
      label: Flavour affected
      options:
        - Steam
        - GOG
        - Vanilla
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - Mac OS X
        - Linux
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: Which version did you experience the bug? (can be found in the bottom-left of the screen)
      options:
        - Alpha 6
        - Alpha 5
        - Alpha 4
        - Alpha 3
        - Alpha 2
        - Alpha 1
    validations:
      required: true
  - type: input
    attributes:
      label: Is it something that used to work before?
      description: If yes, please provide the most recent version where it used to work.
    validations:
        required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: A description of what you expected to happen.
    validations:
        required: true
  - type: textarea
    attributes:
      label: Actual behavior
      description: A description of what is actually happening.
    validations:
        required: true
  - type: textarea
    attributes:
      label: Repro steps
      placeholder: |
        A description with steps to reproduce the issue.
        1. Step 1
        2. Step 2
    validations:
        required: true
