blank_issues_enabled: false

contact_links:
  - name: Steam Forums
    url: https://steamcommunity.com/app/1857080/discussions/
    about: Discuss the Game on the Steam Forums
  - name: Introversion Website
    url: https://www.introversion.co.uk/
    about: Discover Introversion Games
