name: "Issue Labeler"
on:
  issues:
    types: [opened, edited]

jobs:
  version-labeler:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - uses: actions/checkout@v3

      - name: Parse issue form
        uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/bug.yml

      - name: Set labels based on severity field
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v2.0.4
        with:
          issue-form: ${{ steps.issue-parser.outputs.jsonString }}
          section: version
          token: ${{ secrets.GITHUB_TOKEN }}

  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: github/issue-labeler@v3.0 #May not be the latest version
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml
        not-before: 2020-01-15T02:54:32Z
        enable-versioned-regex: 0
