name: "Issue Labeler"
on:
  issues:
    types: [opened, edited]

jobs:
  auto-labeler:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - uses: actions/checkout@v3

      - name: Parse issue form
        uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/bug-report.yml

      - name: Set labels based on flavour field
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v2.0.4
        with:
          issue-form: ${{ steps.issue-parser.outputs.jsonString }}
          section: flavour
          # it says block-list is optional, but it gives a minLength error without it
          block-list: |
            None
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set labels based on OS field
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v2.0.4
        with:
          issue-form: ${{ steps.issue-parser.outputs.jsonString }}
          section: os
          # it says block-list is optional, but it gives a minLength error without it
          block-list: |
            None
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set labels based on version field
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v2.0.4
        with:
          issue-form: ${{ steps.issue-parser.outputs.jsonString }}
          section: version
          # it says block-list is optional, but it gives a minLength error without it
          block-list: |
            None
          token: ${{ secrets.GITHUB_TOKEN }}
